services:
  init:
    build: .
    container_name: retail_data_init
    command: ["python", "generate_data.py"]
    volumes:
      - data:/app/data
  app:
    build: .
    container_name: langgraph_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - data:/app/data
    depends_on:
      - init
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5