services:
  app:
    build: .
    container_name: langgraph_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5